const dataArr = [];
class inputData {
    constructor(eng, kor){
        this.eng = eng;
        this.kor = kor;
    }
}
dataArr.push(new inputData('Seoul,KR', '서울'))
dataArr.push(new inputData('Incheon,KR', '인천'))



dataArr.push(new inputData('Busan,KR', '부산'))
dataArr.push(new inputData('Daegu,KR', '대구'))
dataArr.push(new inputData('Gwangju,KR', '광주'))
dataArr.push(new inputData('Daejeon,KR', '대전'))
dataArr.push(new inputData('Ulsan,KR', '울산'))
dataArr.push(new inputData('Jeju,KR', '제주'))
dataArr.push(new inputData('Sejong,KR', '세종'))
dataArr.push(new inputData('Andong,KR', '안동'))
dataArr.push(new inputData('Ansan,KR', '안산'))
dataArr.push(new inputData('Anseong,KR', '안성'))
dataArr.push(new inputData('Anyang-si,KR', '안양'))
dataArr.push(new inputData('Iksan,KR', '익산'))
dataArr.push(new inputData('Asan,KR', '아산'))
dataArr.push(new inputData('Boryeong,KR', '보령'))
dataArr.push(new inputData('Changwon,KR', '창원'))
dataArr.push(new inputData('Cheongju,KR', '청주'))
dataArr.push(new inputData('Chuncheon,KR', '춘천'))
dataArr.push(new inputData('Chungju,KR', '충주'))
dataArr.push(new inputData('Dongducheon-si,KR', '동두천'))
dataArr.push(new inputData('Gangneung,KR', '강릉'))
dataArr.push(new inputData('Gimcheon,KR', '김천'))
dataArr.push(new inputData('Gimhae,KR', '김해'))
dataArr.push(new inputData('Gimje,KR', '김제'))
dataArr.push(new inputData('Gimpo-si,KR', '김포'))
dataArr.push(new inputData('Gongju,KR', '공주'))
dataArr.push(new inputData('Goyang,KR', '고양'))
dataArr.push(new inputData('Gumi,KR', '구미'))
dataArr.push(new inputData('Gunpo,KR', '군포'))
dataArr.push(new inputData('Gunsan,KR', '군산'))
dataArr.push(new inputData('Guri-si,KR', '구리'))
dataArr.push(new inputData('Gwacheon,KR', '과천'))
dataArr.push(new inputData('Gwangju,KR', '광주'))
dataArr.push(new inputData('Gwangmyeong-si,KR', '광명'))
dataArr.push(new inputData('Gwangyang,KR', '광양'))
dataArr.push(new inputData('Gyeongju,KR', '경주'))
dataArr.push(new inputData('Gyeongsan,KR', '경산'))
dataArr.push(new inputData('Gyeryong-si,KR', '계룡'))
dataArr.push(new inputData('Hanam,KR', '하남'))
dataArr.push(new inputData('Hwaseong,KR', '화성'))
dataArr.push(new inputData('Icheon-si,KR', '이천'))
dataArr.push(new inputData('Jecheon,KR', '제천'))
dataArr.push(new inputData('Jeonju,KR', '전주'))
dataArr.push(new inputData('Jinju,KR', '진주'))
dataArr.push(new inputData('Naju,KR', '나주'))
dataArr.push(new inputData('Namyangju,KR', '남양주'))
dataArr.push(new inputData('Namwon,KR', '남원'))
dataArr.push(new inputData('Nonsan,KR', '논산'))
dataArr.push(new inputData('Miryang,KR', '밀양'))
dataArr.push(new inputData('Mokpo,KR', '목포'))
dataArr.push(new inputData('Mungyeong,KR', '문경'))
dataArr.push(new inputData('Osan,KR', '오산'))
dataArr.push(new inputData('Paju,KR', '파주'))
dataArr.push(new inputData('Pocheon-si,KR', '포천'))
dataArr.push(new inputData('Pohang,KR', '포항'))
dataArr.push(new inputData('Pyeongtaek,KR', '평택'))
dataArr.push(new inputData('Sacheon,KR', '사천'))
dataArr.push(new inputData('Sangju,KR', '상주'))
dataArr.push(new inputData('samcheok,KR', '삼척'))
dataArr.push(new inputData('Seongnam,KR', '성남'))
dataArr.push(new inputData('Seosan,KR', '서산'))
dataArr.push(new inputData('Siheung-si,KR', '시흥'))
dataArr.push(new inputData('Sokcho,KR', '속초'))
dataArr.push(new inputData('Suncheon,KR', '순천'))
dataArr.push(new inputData('Suwon,KR', '수원'))
dataArr.push(new inputData('Taebaek,KR', '태백'))
dataArr.push(new inputData('Uijeongbu-si,KR', '의정부'))
dataArr.push(new inputData('Uiwang,KR', '의왕'))
dataArr.push(new inputData('Wonju,KR', '원주'))
dataArr.push(new inputData('Yangju,KR', '양주'))
dataArr.push(new inputData('Yangsan,KR', '양산'))
dataArr.push(new inputData('Yeoju,KR', '여주'))
dataArr.push(new inputData('Yeongju,KR', '영주'))
dataArr.push(new inputData('Yeosu,KR', '여수'))
dataArr.push(new inputData('Yongin,KR', '용인'))

dataArr.push(new inputData('new york', '뉴욕'))
dataArr.push(new inputData('Vietnam', '베트남'))
dataArr.push(new inputData('London', '런던'))

export default dataArr;